---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---
```{r}
library(here)
library(tidyverse)
library(ggplot2)
library(naniar)
library(eeptools)

getwd()


birthpercent.df <- read.csv(here('Data','Raw','BirthPercent.csv'),stringsAsFactors = TRUE, colClasses = c('CountyFIPS' = 'factor','StateFIPS'='factor'), na.strings = c("Suppressed","No Events"))

```

```{r}
summary(birthpercent.df)
```
```{r}
birthpercent_removed <- na.omit(birthpercent.df)
summary(birthpercent_removed)
```

```{r}

birthpercent_removed$Year <- as.factor(birthpercent_removed$Year)

```


```{r}
birthpercentfinal <- filter(birthpercent_removed,Year!="2001",Year!="2002",Year!="2000",Year!="2003",Year!="2004")

counties <- c("Amador",
              "Alameda",
              "Butte",
              "Contra Costa",
              "Fresno",
              "Humboldt",
              "Imperial",
              "Kern",
              "Kings",
              "Lake",
              "Los Angeles",
              "Mendocino",
              "Merced",
              "Monterey",
              "Nevada",
              "Orange",
              "Placer",
              "Riverside",
              "Sacramento",
              "San Bernardino",
              "San Diego",
              "San Francisco",
              "San Joaquin",
              "San Luis Obispo",
              "San Mateo",
              "Santa Barbara",
              "Santa Clara",
              "Santa Cruz",
              "Shasta",
              "Solano",
              "Sonoma",
              "Stanislaus",
              "Sutter",
              "Tulare",
              "Ventura",
              "Yolo")

birth_percent_county <- birthpercentfinal %>%
  filter(`County` %in% counties)
```

```{r}
Birthpercent_heatmap <- ggplot(birthpercent_removed, aes(x = Year, y = County, fill = Value)) +
  geom_tile() +
  scale_fill_distiller(name = "% Birthweight", palette = "RdYlGn", 
                      direction = -1)
Birthpercent_heatmap
```
```{r}

write.csv(birthpercentfinal, row.names = FALSE, 
          file = "./Data/Processed/birth_percent_Processed.csv")

write.csv(birth_percent_county, row.names = FALSE, 
          file = "./Data/Processed/birth_percent_counties_Processed.csv")

```

